Fixed ZoomRoomIssueDetails and replaced enum with dumb string
Jericho/ZoomNet pull request #135
Opened 2021-05-26 19:44 UTC by vesuvian

1. I was getting bad feedback from the room issues API endpoints because of bad JsonProperties, so I fixed those
2. Some of the properties were badly named so I corrected them
3. I understand the decision to represent the IssueType as an enum, but I'm concerned about Zoom eventually adding new values, changing existing values, or even implementing localization. I elected to remove the IssueType enum and instead use a string, but I'll understand if you want this part reverted.

2021-05-27 13:02 UTC, Jericho commented
Please make sure there's a corresponding issue in order for this PR to be documented in the release notes when it gets merged.

2021-05-27 18:49 UTC, Jericho requested changes
Thanks for your contribution.

2021-05-27 18:49 UTC, Jericho commented on Source/ZoomNet/Models/IssueType.cs
> -	public enum IssueType
My preference is to preserve this enum.

2021-05-27 18:49 UTC, Jericho commented on Source/ZoomNet/Models/IssuesOfZoomRooms.cs
> -		public IssueType IssueType { get; set; }
I prefer preserving the enum type.

2021-05-27 18:49 UTC, Jericho commented on Source/ZoomNet/Models/ZoomRoomIssueDetails.cs
> -		public IssueType IssueType { get; set; }
I prefer preserving the enum type.

2021-05-27 18:49 UTC, Jericho commented on Source/ZoomNet/Models/ZoomRoomIssueDetails.cs
> +		public DateTime Time { get; set; }
Good catch. Thanks for fixing this.

2021-06-01 14:30 UTC, vesuvian commented
I've reverted back to using the enum

2021-06-01 15:36 UTC, Jericho commented on Source/ZoomNet/Models/IssuesOfZoomRooms.cs
> -		public IssueType IssueType { get; set; }
Thanks for restoring the type

2021-06-01 15:44 UTC, Jericho requested changes
Just two quick comments.

2021-06-01 15:44 UTC, Jericho commented on Source/ZoomNet/Models/IssuesOfZoomRooms.cs
> +		public IssueType IssueName { get; set; }
I realize that the json element from Zoom is called "issue_name", but I think "IssueType" or simply "Type" is a more suitable name for this property in our C# model to describe what this property contains.

2021-06-01 15:44 UTC, Jericho commented on Source/ZoomNet/Models/ZoomRoomIssueDetails.cs
> +		public IssueType Issue { get; set; }
I realize that the json element from Zoom is called "issue" but I think "IssueType" or simply "Type" or something along those line is a more suitable name for this property in our C# model to describe what this property contains.

2021-06-01 15:54 UTC, vesuvian commented
Alright, we should be left with the 2 lines that needed changing

2021-06-01 15:58 UTC, Jericho approved these changes
Looks good to me! 
Thank you for your contribution.

2021-06-01 15:58 UTC, merged